#!/bin/bash

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
  # if there's no database, silently and GRACEFULLY exit
  echo "No database found, but that's OK..."
  exit 0
else
  echo 'Checking if names table exists...'
  TABLES=$(`which mysql` -u"$OPENSHIFT_MYSQL_DB_USERNAME"\
    -p"$OPENSHIFT_MYSQL_DB_PASSWORD"\
    -h "$OPENSHIFT_MYSQL_DB_HOST"\
    -P "$OPENSHIFT_MYSQL_DB_PORT"\
    -e "select * from names;"\
    "$OPENSHIFT_APP_NAME")
  
  # if exit code was 1 then the table isn't there
  if [ $? -eq 1 ] 
  then
    echo 'No tables exist. Populating database.'
    `which mysql` -u"$OPENSHIFT_MYSQL_DB_USERNAME"\
    -p"$OPENSHIFT_MYSQL_DB_PASSWORD"\
    -h "$OPENSHIFT_MYSQL_DB_HOST"\
    -P "$OPENSHIFT_MYSQL_DB_PORT"\
    -e "select * from names;"\
    "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/src/main/resources/database.sql"
  else
    "Database is just fine. Nothing to see here..."
  fi
fi
